# Generated by Django 3.1.12 on 2021-07-01 20:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999999' or '9999999999'. Up to 12 digits allowed.", regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')])),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(max_length=3)),
                ('address', models.TextField()),
                ('adhar_number', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(12), django.core.validators.MinLengthValidator(12)])),
                ('pan_number', models.IntegerField(validators=[django.core.validators.MaxLengthValidator(10), django.core.validators.MinLengthValidator(10)])),
                ('gender', models.CharField(max_length=20)),
                ('date_of_registration', models.DateTimeField(auto_now_add=True)),
                ('validity_status', models.BooleanField()),
                ('next_renewal_date', models.DateField()),
                ('message_sent', models.BooleanField()),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
