# Generated by Django 3.1.12 on 2021-07-02 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210702_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='date_of_registration',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='message_sent',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999999' or '9999999999'. Up to 12 digits allowed.", regex='^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='validity_status',
            field=models.CharField(max_length=20),
        ),
    ]
