# Generated by Django 3.1.12 on 2021-07-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210702_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='adhar_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='age',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='pan_number',
            field=models.CharField(max_length=10),
        ),
    ]
